name: flutter_fps
description: A Flutter library to catch fps.
version: 0.1.0
repository: https://github.com/chenenyu/flutter_fps
publish_to: https://pub.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
